
POST http://localhost:3003/band/signup 
Content-Type: application/json

{
    "name": "Beatles",
    "musicGenre":"Rock",
    "responsible":"John Lennon"
}

###

POST http://localhost:3003/user/signup
Content-Type: application/json

    {
        "name": "Luian",
        "email": "luian_email@hotmail.com",
        "password": "senhaluian",
        "role": "ADMIN"
    }

###

# @name login
POST http://localhost:3003/user/login
Content-Type: application/json

    {
        "email": "luis_email@hotmail.com",
        "password": "senhaluis"
    }

###
@token = {{login.response.body.token}}

POST http://localhost:3003/show/create
Content-Type: application/json
auth: {{token}}

    {
        "weekDay": "FRIDAY",
        "startTime": 16,
        "endTime": 17,
        "bandId": "63ba42b4-1923-4591-b5bc-54ab89a0d319"
    }

###
GET http://localhost:3003/show/info/1c258d15-bda8-4c30-9f5f-693f359df816
auth: {{token}}

###
POST http://localhost:3003/gallery/post
Content-Type: application/json

    {
        "photo": ""
    }