
POST http://localhost:3003/band/signup 
Content-Type: application/json

{
    "name": "Beatles",
    "musicGenre":"Rock",
    "responsible":"John Lennon"
}

###

POST http://localhost:3003/user/signup
Content-Type: application/json

    {
        "name": "Luian",
        "email": "luian_email@hotmail.com",
        "password": "senhaluian",
        "role": "ADMIN"
    }

###

# @name login
POST http://localhost:3003/user/login
Content-Type: application/json

    {
        "email": "luis_email@hotmail.com",
        "password": "senhaluis"
    }

###
POST http://localhost:3003/create/show
Content-Type: application/json

    {
        "week_day": "FRIDAY",
        "start_time": "8",
        "end_time": "9",
        "band_id": "?"
    }